"""scripts/actualizar_saldos_desde_excel_oficial.py - Actualiza loanbooks con
valores EXACTOS del Loan Tape oficial loanbook_roddos_2026-04-28.xlsx.

Para cada loanbook ya en MongoDB (match por loanbook_codigo), actualiza:
  - saldo_pendiente = monto_original (columna T del Excel)
  - saldo_capital, saldo_intereses (separados, del Excel)
  - cuotas_pagadas, cuotas_vencidas, dpd
  - mora_acumulada_cop
  - estado (Current, Early Delinquency, etc.)
  - sub_bucket_semanal, score_riesgo
  - tasa_ea
  - cliente.telefono, cliente.ciudad
  - moto.anio, moto.cilindraje
  - ltv, moto_valor_origen

Garantiza que la cartera total en frontend = $372.845.281 (40 motos + 3 rodantes).

Uso (desde Render Shell):
    cd /opt/render/project/src/backend
    python3 scripts/actualizar_saldos_desde_excel_oficial.py --dry-run
    python3 scripts/actualizar_saldos_desde_excel_oficial.py --ejecutar
"""
from __future__ import annotations
import argparse, asyncio, os, sys, json
from datetime import datetime, timezone

_THIS = os.path.dirname(os.path.abspath(__file__))
_BACKEND = os.path.dirname(_THIS)
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

from motor.motor_asyncio import AsyncIOMotorClient

# 43 docs del Loan Tape oficial — datos embebidos
LOAN_TAPE = json.loads(r'''[
  {
    "codigo": "LB-2026-0001",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573015434981",
    "cliente_ciudad": "Bogota",
    "monto_original": 9354800.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 1554800.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-05",
    "fecha_vencimiento": "2027-03-04",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": "Ivan Echeverri",
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 179900.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "semanal",
    "total_cuotas": 52,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE444"
  },
  {
    "codigo": "LB-2026-0002",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573004613796",
    "cliente_ciudad": "Bogota",
    "monto_original": 10140000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 4390000.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-05",
    "fecha_vencimiento": "2027-09-02",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1160000.0,
    "cuota_periodica": 130000.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE448"
  },
  {
    "codigo": "LB-2026-0003",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573005056127",
    "cliente_ciudad": "Bogota",
    "monto_original": 11692200.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 3892200.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-05",
    "fecha_vencimiento": "2027-09-02",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 149900.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE445"
  },
  {
    "codigo": "LB-2026-0004",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573026699546",
    "cliente_ciudad": "Bogota",
    "monto_original": 11692200.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 3892200.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-05",
    "fecha_vencimiento": "2027-09-02",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 149900.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE446"
  },
  {
    "codigo": "LB-2026-0005",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573204276869",
    "cliente_ciudad": "Bogota",
    "monto_original": 11692200.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 3892200.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-05",
    "fecha_vencimiento": "2027-09-02",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 149900.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE447"
  },
  {
    "codigo": "LB-2026-0006",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573118580746",
    "cliente_ciudad": "Bogota",
    "monto_original": 9354800.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 1554800.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-10",
    "fecha_vencimiento": "2027-03-09",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 179900.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "semanal",
    "total_cuotas": 52,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE449"
  },
  {
    "codigo": "LB-2026-0007",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573009550645",
    "cliente_ciudad": "Bogota",
    "monto_original": 7000000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 1250000.0,
    "cuotas_pagadas": 3,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-24",
    "fecha_vencimiento": "2026-12-22",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1160000.0,
    "cuota_periodica": 350000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "quincenal",
    "total_cuotas": 20,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE450"
  },
  {
    "codigo": "LB-2026-0008",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573152371345",
    "cliente_ciudad": "Bogota",
    "monto_original": 8400000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 600000.0,
    "cuotas_pagadas": 3,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-24",
    "fecha_vencimiento": "2026-12-22",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 420000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "quincenal",
    "total_cuotas": 20,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE451"
  },
  {
    "codigo": "LB-2026-0009",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573005472753",
    "cliente_ciudad": "Bogota",
    "monto_original": 10140000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 4390000.0,
    "cuotas_pagadas": 5,
    "cuotas_vencidas": 1,
    "dpd": 2,
    "mora_acumulada_cop": 4000.0,
    "estado": "Early Delinquency",
    "sub_bucket_semanal": "Grace",
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-06",
    "fecha_entrega": "2026-03-10",
    "fecha_vencimiento": "2027-09-07",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1160000.0,
    "cuota_periodica": 130000.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE452"
  },
  {
    "codigo": "LB-2026-0010",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573046344920",
    "cliente_ciudad": "Bogota",
    "monto_original": 9354800.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 1554800.0,
    "cuotas_pagadas": 4,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-13",
    "fecha_entrega": "2026-03-19",
    "fecha_vencimiento": "2027-03-18",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 179900.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "semanal",
    "total_cuotas": 52,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE453"
  },
  {
    "codigo": "LB-2026-0011",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573207643317",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 4,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-19",
    "fecha_entrega": "2026-03-25",
    "fecha_vencimiento": "2026-12-23",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE456"
  },
  {
    "codigo": "LB-2026-0012",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573209003748",
    "cliente_ciudad": "Bogota",
    "monto_original": 9360000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 1560000.0,
    "cuotas_pagadas": 2,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-16",
    "fecha_entrega": "2026-03-21",
    "fecha_vencimiento": "2027-03-20",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 360000.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "quincenal",
    "total_cuotas": 26,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE454"
  },
  {
    "codigo": "LB-2026-0013",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573102411685",
    "cliente_ciudad": "Bogota",
    "monto_original": 0.0,
    "saldo_capital": 0.0,
    "saldo_intereses": 0.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Pagado",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-17",
    "fecha_entrega": "2026-03-20",
    "fecha_vencimiento": "2026-03-27",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 0.0,
    "plan_codigo": "P1S",
    "modalidad_pago": "contado",
    "total_cuotas": 0,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": null
  },
  {
    "codigo": "LB-2026-0014",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573244080412",
    "cliente_ciudad": "Bogota",
    "monto_original": 11692200.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 3892200.0,
    "cuotas_pagadas": 2,
    "cuotas_vencidas": 1,
    "dpd": 1,
    "mora_acumulada_cop": 2000.0,
    "estado": "Early Delinquency",
    "sub_bucket_semanal": "Grace",
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-24",
    "fecha_entrega": "2026-03-27",
    "fecha_vencimiento": "2027-09-24",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 149900.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE457"
  },
  {
    "codigo": "LB-2026-0015",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573507991099",
    "cliente_ciudad": "Bogota",
    "monto_original": 11692200.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 3892200.0,
    "cuotas_pagadas": 3,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-26",
    "fecha_entrega": "2026-03-27",
    "fecha_vencimiento": "2027-09-24",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 149900.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE459"
  },
  {
    "codigo": "LB-2026-0016",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573011264063",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 3,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-24",
    "fecha_entrega": "2026-03-27",
    "fecha_vencimiento": "2026-12-25",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE461"
  },
  {
    "codigo": "LB-2026-0017",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573155237548",
    "cliente_ciudad": "Bogota",
    "monto_original": 5069961.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": -2730039.0,
    "cuotas_pagadas": 3,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-25",
    "fecha_entrega": "2026-03-28",
    "fecha_vencimiento": "2026-12-26",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 129999.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE458"
  },
  {
    "codigo": "LB-2026-0018",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573507541578",
    "cliente_ciudad": "Bogota",
    "monto_original": 12861420.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 5061420.0,
    "cuotas_pagadas": 1,
    "cuotas_vencidas": 1,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-25",
    "fecha_entrega": "2026-03-28",
    "fecha_vencimiento": "2027-09-25",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 329780.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "quincenal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE460"
  },
  {
    "codigo": "LB-2026-0019",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573223257977",
    "cliente_ciudad": "Bogota",
    "monto_original": 12861420.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 5061420.0,
    "cuotas_pagadas": 1,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-06",
    "fecha_entrega": "2026-04-08",
    "fecha_vencimiento": "2027-10-06",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 329780.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "quincenal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE462"
  },
  {
    "codigo": "LB-2026-0020",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573246300165",
    "cliente_ciudad": "Bogota",
    "monto_original": 10290280.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 2490280.0,
    "cuotas_pagadas": 1,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-07",
    "fecha_entrega": "2026-04-10",
    "fecha_vencimiento": "2027-04-09",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 395780.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "quincenal",
    "total_cuotas": 26,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE463"
  },
  {
    "codigo": "LB-2026-0021",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573161067357",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 2,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-08",
    "fecha_entrega": "2026-04-10",
    "fecha_vencimiento": "2027-01-08",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE464"
  },
  {
    "codigo": "LB-2026-0022",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573054510615",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 1,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-08",
    "fecha_entrega": "2026-04-10",
    "fecha_vencimiento": "2027-01-08",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE465"
  },
  {
    "codigo": "LB-2026-0023",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573175127527",
    "cliente_ciudad": "Bogota",
    "monto_original": 11692200.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 3892200.0,
    "cuotas_pagadas": 1,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-08",
    "fecha_entrega": "2026-04-10",
    "fecha_vencimiento": "2027-10-08",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 149900.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE466"
  },
  {
    "codigo": "LB-2026-0027",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573155237548",
    "cliente_ciudad": "Bogota",
    "monto_original": 11310000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 5560000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-15",
    "fecha_entrega": "2026-04-20",
    "fecha_vencimiento": "2027-10-18",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0.0,
    "cuota_periodica": 145000.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE467"
  },
  {
    "codigo": "LB-2026-0028",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573024743216",
    "cliente_ciudad": "Bogota",
    "monto_original": 7956000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 2206000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-16",
    "fecha_entrega": "2026-04-21",
    "fecha_vencimiento": "2027-01-19",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0.0,
    "cuota_periodica": 204000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE468"
  },
  {
    "codigo": "LB-2026-0029",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573214383749",
    "cliente_ciudad": "Bogota",
    "monto_original": 7956000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 2206000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-17",
    "fecha_entrega": "2026-04-20",
    "fecha_vencimiento": "2027-01-18",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0.0,
    "cuota_periodica": 204000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE469"
  },
  {
    "codigo": "LB-2026-0030",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573232256737",
    "cliente_ciudad": "Bogota",
    "monto_original": 9464000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 3714000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-17",
    "fecha_entrega": "2026-04-20",
    "fecha_vencimiento": "2027-04-19",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0.0,
    "cuota_periodica": 182000.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "semanal",
    "total_cuotas": 52,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE470"
  },
  {
    "codigo": "LB-2026-0031",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573115035599",
    "cliente_ciudad": "Bogota",
    "monto_original": 6825000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 1075000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-20",
    "fecha_entrega": "2026-04-23",
    "fecha_vencimiento": "2027-01-21",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 550000.0,
    "cuota_periodica": 175000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE471"
  },
  {
    "codigo": "LB-2026-0032",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573044395444",
    "cliente_ciudad": "Bogota",
    "monto_original": 11310000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 5560000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-23",
    "fecha_entrega": "2026-04-29",
    "fecha_vencimiento": "2027-10-27",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0.0,
    "cuota_periodica": 145000.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE472"
  },
  {
    "codigo": "LB-2026-0033",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573228366769",
    "cliente_ciudad": "Bogota",
    "monto_original": 7956000.0,
    "saldo_capital": 5750000.0,
    "saldo_intereses": 2206000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-23",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0.0,
    "cuota_periodica": 204000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 100,
    "moto_valor_origen": 4157461.0,
    "ltv": 0,
    "factura_alegra_id": "FE473"
  },
  {
    "codigo": "LB-2026-0034",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573239469837",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-27",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE474"
  },
  {
    "codigo": "LB-2026-0035",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573046627605",
    "cliente_ciudad": "Bogota",
    "monto_original": 11692200.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 3892200.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-27",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 149900.0,
    "plan_codigo": "P78S",
    "modalidad_pago": "semanal",
    "total_cuotas": 78,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE475"
  },
  {
    "codigo": "LB-2026-0036",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573145204952",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-27",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE476"
  },
  {
    "codigo": "LB-2026-0037",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573249063599",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-28",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE477"
  },
  {
    "codigo": "LB-2026-0038",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573249063599",
    "cliente_ciudad": "Bogota",
    "monto_original": 9354800.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 1554800.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-28",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 179900.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "semanal",
    "total_cuotas": 52,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE478"
  },
  {
    "codigo": "LB-2026-0039",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573249063599",
    "cliente_ciudad": "Bogota",
    "monto_original": 9354800.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 1554800.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-28",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 179900.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "semanal",
    "total_cuotas": 52,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE479"
  },
  {
    "codigo": "LB-2026-0040",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573003319158",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-28",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE480"
  },
  {
    "codigo": "LB-2026-0041",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573224113327",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-28",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE481"
  },
  {
    "codigo": "LB-2026-0042",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573001758140",
    "cliente_ciudad": "Bogota",
    "monto_original": 8190000.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 390000.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-28",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 210000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE482"
  },
  {
    "codigo": "LB-2026-0043",
    "producto": "RDX",
    "subtipo_rodante": null,
    "cliente_telefono": "573004801153",
    "cliente_ciudad": "Bogota",
    "monto_original": 9354800.0,
    "saldo_capital": 7800000.0,
    "saldo_intereses": 1554800.0,
    "cuotas_pagadas": 0,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "pendiente_entrega",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-04-28",
    "fecha_entrega": null,
    "fecha_vencimiento": null,
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 1460000.0,
    "cuota_periodica": 179900.0,
    "plan_codigo": "P52S",
    "modalidad_pago": "semanal",
    "total_cuotas": 52,
    "moto_anio": 2027,
    "moto_cilindraje": 125,
    "moto_valor_origen": 5638974.0,
    "ltv": 0,
    "factura_alegra_id": "FE483"
  },
  {
    "codigo": "LB-2026-0024",
    "producto": "RODANTE",
    "subtipo_rodante": "comparendo",
    "cliente_telefono": "573004613796",
    "cliente_ciudad": "",
    "monto_original": 1050000.0,
    "saldo_capital": 560000.0,
    "saldo_intereses": 0.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-05",
    "fecha_vencimiento": "2026-06-17",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0,
    "cuota_periodica": 70000.0,
    "plan_codigo": "P15S",
    "modalidad_pago": "semanal",
    "total_cuotas": 15,
    "moto_anio": null,
    "moto_cilindraje": null,
    "moto_valor_origen": 0,
    "ltv": 0,
    "factura_alegra_id": null
  },
  {
    "codigo": "LB-2026-0025",
    "producto": "RODANTE",
    "subtipo_rodante": "comparendo",
    "cliente_telefono": "573026699546",
    "cliente_ciudad": "",
    "monto_original": 1500000.0,
    "saldo_capital": 800000.0,
    "saldo_intereses": 0.0,
    "cuotas_pagadas": 6,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-02",
    "fecha_entrega": "2026-03-05",
    "fecha_vencimiento": "2026-06-17",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0,
    "cuota_periodica": 100000.0,
    "plan_codigo": "P15S",
    "modalidad_pago": "semanal",
    "total_cuotas": 15,
    "moto_anio": null,
    "moto_cilindraje": null,
    "moto_valor_origen": 0,
    "ltv": 0,
    "factura_alegra_id": null
  },
  {
    "codigo": "LB-2026-0026",
    "producto": "RODANTE",
    "subtipo_rodante": "licencia",
    "cliente_telefono": "573207643317",
    "cliente_ciudad": "",
    "monto_original": 1521000.0,
    "saldo_capital": 1326000.0,
    "saldo_intereses": 0.0,
    "cuotas_pagadas": 4,
    "cuotas_vencidas": 0,
    "dpd": 0,
    "mora_acumulada_cop": 0.0,
    "estado": "Current",
    "sub_bucket_semanal": null,
    "score_riesgo": null,
    "tasa_ea": 0.39,
    "fecha_factura": "2026-03-19",
    "fecha_entrega": "2026-03-25",
    "fecha_vencimiento": "2026-12-02",
    "fecha_ultimo_pago": null,
    "whatsapp_status": "pending",
    "vendedor": null,
    "cuota_inicial": 0,
    "cuota_periodica": 39000.0,
    "plan_codigo": "P39S",
    "modalidad_pago": "semanal",
    "total_cuotas": 39,
    "moto_anio": null,
    "moto_cilindraje": null,
    "moto_valor_origen": 0,
    "ltv": 0,
    "factura_alegra_id": null
  }
]''')


async def main(args):
    mongo = os.environ.get("MONGO_URL", "")
    db_name = os.environ.get("DB_NAME", "")
    if not mongo or not db_name:
        print("ERROR: MONGO_URL o DB_NAME no configurados")
        sys.exit(1)

    cli = AsyncIOMotorClient(mongo)
    db = cli[db_name]
    ahora = datetime.now(timezone.utc)
    actualizados = 0
    no_encontrados = []

    print(f"\n{'='*100}")
    print(f"{'codigo':<14}{'cliente':<32}{'monto_orig':>14}{'cap':>12}{'int':>12}{'cuotas':>9}{'dpd':>5}{'estado':<22}")
    print(f"{'='*100}")

    try:
        for d in LOAN_TAPE:
            existing = await db.loanbook.find_one({"loanbook_id": d["codigo"]})
            if not existing:
                no_encontrados.append(d["codigo"])
                continue

            cliente_nombre = (existing.get("cliente") or {}).get("nombre") or existing.get("cliente_nombre", "?")
            print(f"{d['codigo']:<14}{cliente_nombre[:30]:<32}"
                  f"{d['monto_original']:>14,.0f}{d['saldo_capital']:>12,.0f}"
                  f"{d['saldo_intereses']:>12,.0f}"
                  f"{d['cuotas_pagadas']}/{d['total_cuotas']:<5}"
                  f"{d['dpd']:>5}{d['estado'][:20]:<22}")

            if not args.ejecutar:
                continue

            update = {
                # Saldos EXACTOS del Excel
                "saldo_pendiente":     int(d["monto_original"]),  # ← columna T
                "saldo_capital":       int(d["saldo_capital"]),
                "saldo_intereses":     int(d["saldo_intereses"]),
                "monto_original":      int(d["monto_original"]),
                "valor_total":         int(d["monto_original"]),
                "mora_acumulada_cop":  int(d["mora_acumulada_cop"]),

                # Pagos y mora
                "cuotas_pagadas":      d["cuotas_pagadas"],
                "cuotas_vencidas":     d["cuotas_vencidas"],
                "cuotas_total":        d["total_cuotas"],
                "dpd":                 d["dpd"],

                # Estados
                "estado":              d["estado"],
                "sub_bucket_semanal":  d.get("sub_bucket_semanal"),
                "score_riesgo":        d.get("score_riesgo"),

                # Tasa
                "tasa_ea":             d["tasa_ea"],
                "ltv":                 d.get("ltv", 0),
                "moto_valor_origen":   int(d.get("moto_valor_origen", 0)),

                # Whatsapp
                "whatsapp_status":     d.get("whatsapp_status", "pending"),
                "fecha_ultimo_pago":   d.get("fecha_ultimo_pago"),
                "vendedor":            d.get("vendedor"),
                "fecha_vencimiento":   d.get("fecha_vencimiento"),

                # Auditoria
                "updated_at":          ahora.isoformat(),
                "synced_from_excel_oficial": ahora.isoformat(),
            }

            # Set anidados (cliente.telefono, cliente.ciudad, moto.anio, moto.cilindraje)
            if d.get("cliente_telefono"):
                update["cliente.telefono"] = d["cliente_telefono"]
            if d.get("cliente_ciudad"):
                update["cliente.ciudad"] = d["cliente_ciudad"]
            if d.get("moto_anio"):
                update["moto.anio"] = d["moto_anio"]
            if d.get("moto_cilindraje"):
                update["moto.cilindraje"] = d["moto_cilindraje"]

            # Plan anidado: cuota_valor, cuota_inicial, codigo, modalidad
            update["plan.codigo"] = d["plan_codigo"]
            update["plan.modalidad"] = d["modalidad_pago"]
            update["plan.cuota_valor"] = int(d["cuota_periodica"])
            update["plan.cuota_inicial"] = int(d["cuota_inicial"])
            update["plan.total_cuotas"] = d["total_cuotas"]

            # Fechas anidadas
            update["fechas.factura"] = d.get("fecha_factura")
            update["fechas.entrega"] = d.get("fecha_entrega")
            update["fecha_vencimiento"] = d.get("fecha_vencimiento")

            await db.loanbook.update_one(
                {"loanbook_id": d["codigo"]},
                {"$set": update},
            )
            actualizados += 1

        # Verificacion final
        if args.ejecutar:
            total = 0.0
            n = 0
            async for lb in db.loanbook.find({}, {"saldo_pendiente": 1}):
                total += lb.get("saldo_pendiente", 0) or 0
                n += 1
            print(f"\n{'='*60}")
            print(f"VERIFICACION POST-UPDATE:")
            print(f"  Total loanbooks en DB:      {n}")
            print(f"  Σ saldo_pendiente:          ${total:,.0f}")
            print(f"  Target Excel (40+3):        $372,845,281")
            print(f"  Delta:                      ${total - 372845281:+,.0f}")
            print(f"{'='*60}")

        print(f"\nRESUMEN ({'EJECUCION REAL' if args.ejecutar else 'DRY-RUN'}):")
        print(f"  Total filas Excel:    {len(LOAN_TAPE)}")
        print(f"  Actualizados:         {actualizados}")
        if no_encontrados:
            print(f"  No encontrados ({len(no_encontrados)}):")
            for c in no_encontrados:
                print(f"    {c}")
        if not args.ejecutar:
            print("\nPara ejecutar real: python3 scripts/actualizar_saldos_desde_excel_oficial.py --ejecutar")
    finally:
        cli.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--ejecutar", action="store_true")
    args = parser.parse_args()
    asyncio.run(main(args))
